dependencies:
  - type: olm.package
    value:
      packageName: csi-addons
      version: '>=0.9.1'
  - type: olm.package
    value:
      packageName: cephcsi-operator
      version: 4.17.0
  - type: olm.package
    value:
      packageName: noobaa-operator
      version: ">=5.16.0 <=5.17.0"
