apiVersion: ocs.openshift.io/v1alpha1
kind: StorageClient
metadata:
  labels:
    app.kubernetes.io/name: storageclient
    app.kubernetes.io/instance: storageclient-sample
    app.kubernetes.io/part-of: ocs-client-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: ocs-client-operator
  name: storageclient-sample
spec:
  # TODO(user): Add fields here
