---
name: golangci-lint

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: ["1.17", "1.18"]
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or
          # v1.2.3 or `latest` to use the latest version
          version: latest

          # Optional: working directory, useful for monorepos
          # working-directory: somedir

          # Optional: golangci-lint command line arguments.
          # TODO: --out-format=github-action is enforced but doesn't print
          # file names or line numbers. Watch for fix in Issue:
          # https://github.com/golangci/golangci-lint-action/issues/119
          #
          # The weird NO_FUTURE thing is a workaround suggested here:
          # https://github.com/golangci/golangci-lint-action/issues/119#issuecomment-981090648
          args: "--out-${NO_FUTURE}format=colored-line-number"

          # Optional: show only new issues if it's a pull request.
          # The default value is `false`.
          # only-new-issues: true

          # Optional: if set to true then the action will use pre-installed Go.
          skip-go-installation: true

          # Optional: if set to true then the action don't cache or
          # restore ~/go/pkg.
          # skip-pkg-cache: true

          # Optional: if set to true then the action don't cache or
          # restore ~/.cache/go-build.
          # skip-build-cache: true
